/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BaseDatos.bdReportes;
import Metodos.BloquearTxt;
import java.awt.Color;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Sti
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form Ihterfaz
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        formWindowOpened(null);
        // Convertir el texto ingresado a Mayuscula
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new KeyEventDispatcher() {
            public boolean dispatchKeyEvent(KeyEvent e) {

                if (e.getID() == KeyEvent.KEY_TYPED)//las notificaciones del tipo "typed" son las que actualizan los componentes
                {
                    if (e.getKeyChar() >= 'a' && e.getKeyChar() <= 'z') {
                        //si lo son, entonces lo reemplazamos por su respectivo en mayúscula en el mismo evento
                        e.setKeyChar((char) (((int) e.getKeyChar()) - 32));
                    }
                }
                return false;
            }
        });
    }
    int aBasica = 0;
    String paralelo;
    String x = "";
    String cedula;
    BloquearTxt metodo = new BloquearTxt();

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        timer = new Timer(1000, new cronometro());
        timer.start();
    }

    public class cronometro implements ActionListener {

        public void actionPerformed(ActionEvent evt) {
            GregorianCalendar tiempo = new GregorianCalendar();
            int hora, minutos, segundos;
            hora = tiempo.get(Calendar.HOUR);
            minutos = tiempo.get(Calendar.MINUTE);
            segundos = tiempo.get(Calendar.SECOND);
            lbHora.setText(String.valueOf(hora) + ":" + String.valueOf(minutos) + ":" + String.valueOf(segundos));
            DateFormat df = DateFormat.getDateInstance();
            Date fecha = new Date();
            lbFecha.setText(df.format(fecha));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ayuda = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Creditos = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        frmNomina = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbABasica = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtParalelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnVerNomina = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        frmRegistros = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnEstudiante = new javax.swing.JButton();
        btnInasistencia = new javax.swing.JButton();
        btnDetallesAsig = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbABasica1 = new javax.swing.JComboBox();
        btnBuscar1 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMatricula = new javax.swing.JButton();
        btnRegistrarPersona = new javax.swing.JButton();
        btnCalificaiones = new javax.swing.JButton();
        btnComisiones = new javax.swing.JButton();
        btnAsignaturas = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnVisualizarPersonas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnModificarPersonas = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        jPanelFecha = new javax.swing.JPanel();
        lbFecha = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnSalirSistema = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        fondoMenu = new javax.swing.JLabel();

        Ayuda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AYUDA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Question.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Ayuda.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 60));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("INFORMACION DEL MENU\nREGISTRAR PERSONA\nRegistra los datos personales de las personas que forman parte de la entidad educativa como:estudiantes, profesores, empleados.\n\nMODIFICAR PERSONA\nEn caso de actualizacion o edicion de datos se puede modificar a una persona ya registrada.\nVISUALIZAR REGISTROS\nDe acuerdo al tipo de persona se visualiza mediante un regisro los datos relevantes.\n\nCOMISIONES\nAgregar, buscar, eliminar y modificar las comisiones que se registren en la unidad educativa.\n\nASIGNATURAS\nSe puede agregar, visualizar y modificar de acuerdo al año de educacion básica.\n\nCURSO\nRegistrar los cursos que la entidad educativa posee, en la cual se puede establecer el horario de clases respectivo.\n\nASISTENCIA\nDe acuerdo al curso que hay registrado en la escuela se visualiza los estudiantes que pertenencen a dicho salón de clases, en donde en caso de inasistencia se puede registar dicha acción.\n\nGENERAR MATRICULA\nPara matricular y designar a un estudiante en su respectivo curso.\n\nREPORTE\nDatos relevantes de los registros  guardados.");
        jScrollPane1.setViewportView(jTextArea1);

        Ayuda.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 400, 370));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pensando.gif"))); // NOI18N
        Ayuda.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 340, 360));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("INFORMACIÓN");
        Ayuda.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 30));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Escuela de Educación Basica \"Angel Polivio Márquez P.\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Ayuda.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 640, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazul.jpg"))); // NOI18N
        Ayuda.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 450));

        Creditos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordenador.gif"))); // NOI18N
        Creditos.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 170, 190));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/creditos.png"))); // NOI18N
        Creditos.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frmNomina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("REGISTROS");
        frmNomina.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR", "ESTUDIANTES", "PROFESORES", "EMPLEADOS" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        frmNomina.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, -1));

        jPanel4.setFocusable(false);
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Año Ed.Básica:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cbABasica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR", "PRIMERO", "SEGUNDO", "TERCERO", "CUARTO", "QUINTO", "SEXTO", "SEPTIMO" }));
        cbABasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbABasicaActionPerformed(evt);
            }
        });
        jPanel4.add(cbABasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Paralelo:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        txtParalelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtParaleloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParaleloKeyTyped(evt);
            }
        });
        jPanel4.add(txtParalelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 40, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Seleccione el curso:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        frmNomina.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 370, 70));

        btnVerNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchsocio.jpg"))); // NOI18N
        btnVerNomina.setText("ACEPTAR");
        btnVerNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNominaActionPerformed(evt);
            }
        });
        frmNomina.getContentPane().add(btnVerNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Visualizar a:");
        frmNomina.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazul.jpg"))); // NOI18N
        frmNomina.getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 190));

        frmRegistros.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel15.setText("REPORTES");
        frmRegistros.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        btnReporte.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnReporte.setText("CANTIDAD DE ALUMNOS");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        frmRegistros.getContentPane().add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 220, 60));

        btnEstudiante.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnEstudiante.setText("INFORMACION DE UN ESTUDIANTE");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });
        frmRegistros.getContentPane().add(btnEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 220, 60));

        btnInasistencia.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnInasistencia.setText("LISTA DE INASISTENCIA");
        btnInasistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInasistenciaActionPerformed(evt);
            }
        });
        frmRegistros.getContentPane().add(btnInasistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 220, 60));

        btnDetallesAsig.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnDetallesAsig.setText("DETALLES DE LA ASIGNATURA");
        btnDetallesAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesAsigActionPerformed(evt);
            }
        });
        frmRegistros.getContentPane().add(btnDetallesAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 220, 60));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la cédula del estudiante"));
        jPanel5.setOpaque(false);

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("CEDULA:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search32select.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        frmRegistros.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 370, 80));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el curso"));
        jPanel6.setFocusable(false);
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Año Ed.Básica:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cbABasica1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR", "PRIMERO", "SEGUNDO", "TERCERO", "CUARTO", "QUINTO", "SEXTO", "SEPTIMO" }));
        cbABasica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbABasica1ActionPerformed(evt);
            }
        });
        jPanel6.add(cbABasica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search32select.png"))); // NOI18N
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 30, 30));

        frmRegistros.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 370, 70));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazul.jpg"))); // NOI18N
        frmRegistros.getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setOpaque(false);

        btnMatricula.setBackground(new java.awt.Color(153, 204, 255));
        btnMatricula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matricula.png"))); // NOI18N
        btnMatricula.setText("Generar Matricula");
        btnMatricula.setToolTipText("Generar matricula estudiantil");
        btnMatricula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatricula.setDoubleBuffered(true);
        btnMatricula.setFocusCycleRoot(true);
        btnMatricula.setFocusPainted(false);
        btnMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatricula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matricula.png"))); // NOI18N
        btnMatricula.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matricula.png"))); // NOI18N
        btnMatricula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculaActionPerformed(evt);
            }
        });

        btnRegistrarPersona.setBackground(new java.awt.Color(153, 204, 255));
        btnRegistrarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarcliente 2.jpg"))); // NOI18N
        btnRegistrarPersona.setText("Registrar Persona");
        btnRegistrarPersona.setToolTipText("Registar un estudiante,profesor o empleado");
        btnRegistrarPersona.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPersona.setDefaultCapable(false);
        btnRegistrarPersona.setFocusPainted(false);
        btnRegistrarPersona.setFocusable(false);
        btnRegistrarPersona.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarPersona.setIconTextGap(6);
        btnRegistrarPersona.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarcliente.jpg"))); // NOI18N
        btnRegistrarPersona.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarcliente.jpg"))); // NOI18N
        btnRegistrarPersona.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarcliente.jpg"))); // NOI18N
        btnRegistrarPersona.setSelected(true);
        btnRegistrarPersona.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaActionPerformed(evt);
            }
        });

        btnCalificaiones.setBackground(new java.awt.Color(153, 204, 255));
        btnCalificaiones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalificaiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.png"))); // NOI18N
        btnCalificaiones.setText("Calificaciones");
        btnCalificaiones.setToolTipText("Registrar calificaciones");
        btnCalificaiones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalificaiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalificaiones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalificaiones.setInheritsPopupMenu(true);
        btnCalificaiones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.png"))); // NOI18N
        btnCalificaiones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista1.png"))); // NOI18N
        btnCalificaiones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista1.png"))); // NOI18N
        btnCalificaiones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalificaiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificaionesActionPerformed(evt);
            }
        });

        btnComisiones.setBackground(new java.awt.Color(153, 204, 255));
        btnComisiones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnComisiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial.png"))); // NOI18N
        btnComisiones.setText("Comisiones");
        btnComisiones.setToolTipText("Agregar,modificar,buscar,eliminar comisiones");
        btnComisiones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComisiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComisiones.setDoubleBuffered(true);
        btnComisiones.setFocusCycleRoot(true);
        btnComisiones.setFocusPainted(false);
        btnComisiones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComisiones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial1.png"))); // NOI18N
        btnComisiones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial1.png"))); // NOI18N
        btnComisiones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComisionesActionPerformed(evt);
            }
        });

        btnAsignaturas.setBackground(new java.awt.Color(153, 204, 255));
        btnAsignaturas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda1.png"))); // NOI18N
        btnAsignaturas.setText("Asignaturas");
        btnAsignaturas.setToolTipText("Agregar,modificar,buscar,eliminar asignaturas");
        btnAsignaturas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsignaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignaturas.setDoubleBuffered(true);
        btnAsignaturas.setFocusCycleRoot(true);
        btnAsignaturas.setFocusPainted(false);
        btnAsignaturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsignaturas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda.png"))); // NOI18N
        btnAsignaturas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda.png"))); // NOI18N
        btnAsignaturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignaturasActionPerformed(evt);
            }
        });

        btnCurso.setBackground(new java.awt.Color(153, 204, 255));
        btnCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/info1.png"))); // NOI18N
        btnCurso.setText("Curso");
        btnCurso.setToolTipText("Agregar,modificar,buscar,eliminar un curso");
        btnCurso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurso.setDoubleBuffered(true);
        btnCurso.setFocusCycleRoot(true);
        btnCurso.setFocusPainted(false);
        btnCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCurso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/info.png"))); // NOI18N
        btnCurso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/info.png"))); // NOI18N
        btnCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });

        btnVisualizarPersonas.setBackground(new java.awt.Color(153, 204, 255));
        btnVisualizarPersonas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVisualizarPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.gif"))); // NOI18N
        btnVisualizarPersonas.setText("Nómina de entidades");
        btnVisualizarPersonas.setToolTipText("Visualizar lista de personas registradas");
        btnVisualizarPersonas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVisualizarPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizarPersonas.setDefaultCapable(false);
        btnVisualizarPersonas.setFocusPainted(false);
        btnVisualizarPersonas.setFocusable(false);
        btnVisualizarPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisualizarPersonas.setIconTextGap(6);
        btnVisualizarPersonas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.gif"))); // NOI18N
        btnVisualizarPersonas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.gif"))); // NOI18N
        btnVisualizarPersonas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.gif"))); // NOI18N
        btnVisualizarPersonas.setSelected(true);
        btnVisualizarPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVisualizarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarPersonasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(153, 204, 255));
        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        btnReportes.setText("Reporte");
        btnReportes.setToolTipText("Datos de registros");
        btnReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setDoubleBuffered(true);
        btnReportes.setFocusCycleRoot(true);
        btnReportes.setFocusPainted(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes1.png"))); // NOI18N
        btnReportes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes1.png"))); // NOI18N
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnModificarPersonas.setBackground(new java.awt.Color(153, 204, 255));
        btnModificarPersonas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificarPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar_persona.png"))); // NOI18N
        btnModificarPersonas.setText("Modificar Persona");
        btnModificarPersonas.setToolTipText("Editar los datos de una persona registrada");
        btnModificarPersonas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarPersonas.setDefaultCapable(false);
        btnModificarPersonas.setFocusPainted(false);
        btnModificarPersonas.setFocusable(false);
        btnModificarPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarPersonas.setIconTextGap(6);
        btnModificarPersonas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar_persona - copia.png"))); // NOI18N
        btnModificarPersonas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar_persona.png"))); // NOI18N
        btnModificarPersonas.setSelected(true);
        btnModificarPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonasActionPerformed(evt);
            }
        });

        btnAsistencia.setBackground(new java.awt.Color(153, 204, 255));
        btnAsistencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/creditoss.png"))); // NOI18N
        btnAsistencia.setText("Asistencia");
        btnAsistencia.setToolTipText("Nomina de estudiantes para agregar inasistencias");
        btnAsistencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencia.setDoubleBuffered(true);
        btnAsistencia.setFocusCycleRoot(true);
        btnAsistencia.setFocusPainted(false);
        btnAsistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsistencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/creditos_2.png"))); // NOI18N
        btnAsistencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/creditos_2.png"))); // NOI18N
        btnAsistencia.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/creditos_2.png"))); // NOI18N
        btnAsistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalificaiones, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalificaiones, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnVisualizarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 600, 450));

        jPanelFecha.setOpaque(false);

        lbFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("FECHA:");

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("HORA:");

        javax.swing.GroupLayout jPanelFechaLayout = new javax.swing.GroupLayout(jPanelFecha);
        jPanelFecha.setLayout(jPanelFechaLayout);
        jPanelFechaLayout.setHorizontalGroup(
            jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFechaLayout.setVerticalGroup(
            jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 630, 40));

        btnAyuda.setBackground(new java.awt.Color(255, 204, 153));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Question.png"))); // NOI18N
        btnAyuda.setToolTipText("Ayuda");
        btnAyuda.setBorderPainted(false);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 40, -1));

        btnSalirSistema.setBackground(new java.awt.Color(255, 204, 153));
        btnSalirSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_salir.png"))); // NOI18N
        btnSalirSistema.setToolTipText("Cerrar programa");
        btnSalirSistema.setBorderPainted(false);
        btnSalirSistema.setContentAreaFilled(false);
        btnSalirSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 70, 70));

        btnCreditos.setBackground(new java.awt.Color(255, 204, 153));
        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Information.png"))); // NOI18N
        btnCreditos.setToolTipText("Creditos");
        btnCreditos.setBorderPainted(false);
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 40, -1));

        fondoMenu.setBackground(new java.awt.Color(204, 204, 255));
        fondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_esc.png"))); // NOI18N
        getContentPane().add(fondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
//        frmCurso curso = new frmCurso();
//        curso.setVisible(true);
//        curso.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCursoActionPerformed

    private void btnAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignaturasActionPerformed
        frmAsignaturas asig = new frmAsignaturas();
        asig.setVisible(true);
        asig.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAsignaturasActionPerformed

    private void btnComisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComisionesActionPerformed
        // TODO add your handling code here:
        frmComision comision = new frmComision();
        comision.setVisible(true);
        comision.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnComisionesActionPerformed

    private void btnCalificaionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificaionesActionPerformed
//        frmCalificaciones ca= new frmCalificaciones();
//        ca.setVisible(true);
//        ca.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCalificaionesActionPerformed

    private void btnRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaActionPerformed
//        frmRegistarPersona persona= new frmRegistarPersona();
//        persona.setVisible(true);
//        persona.pack();
//        persona.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistrarPersonaActionPerformed

    private void btnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculaActionPerformed
//        // TODO add your handling code here:
//        frmMatricula fm=new frmMatricula();
//        fm.setVisible(true);
//        fm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMatriculaActionPerformed

    private void btnVisualizarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarPersonasActionPerformed
        frmNomina.setVisible(true);
        frmNomina.pack();
        frmNomina.setLocationRelativeTo(null);
        jPanel4.setVisible(false);

    }//GEN-LAST:event_btnVisualizarPersonasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        frmRegistros.setVisible(true);
        frmRegistros.pack();
        frmRegistros.setLocationRelativeTo(null);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnModificarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonasActionPerformed
//       frmModificarPersona editar = new frmModificarPersona();
//       editar.setVisible(true);
//       editar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnModificarPersonasActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        frmAsistencia as = new frmAsistencia();
        as.setVisible(true);
        as.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        Creditos.pack();
        Creditos.setVisible(true);
        Creditos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Ayuda.pack();
        Ayuda.setVisible(true);
        Ayuda.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirSistemaActionPerformed

    private void cbABasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbABasicaActionPerformed

    }//GEN-LAST:event_cbABasicaActionPerformed

    private void txtParaleloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParaleloKeyPressed

    }//GEN-LAST:event_txtParaleloKeyPressed

    private void txtParaleloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParaleloKeyTyped
        metodo.SoloLetras(evt, txtParalelo);
        if (txtParalelo.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtParaleloKeyTyped

    private void btnVerNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNominaActionPerformed
        x = (String) jComboBox1.getSelectedItem();
        if (x.equals("SELECCIONAR")) {
            JOptionPane.showMessageDialog(null, "Seleccione el registro que desee ver");
        }
        if (x.equals("ESTUDIANTES")) {
            if (txtParalelo.getText().isEmpty() && cbABasica.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Escoga el curso a visualizar ");

            } else {
                try {
                    aBasica = metodo.Numero_añoBas(cbABasica);
                    paralelo = txtParalelo.getText();
                    String cp = aBasica + paralelo;
                    bdReportes.reporteNomina(cp);
                } catch (JRException ex) {
                    Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (x.equals("PROFESORES")) {
            try {
                bdReportes.reporteProfesores();
            } catch (JRException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (x.equals("EMPLEADOS")) {
            try {
                bdReportes.reporteEmpleados();
            } catch (JRException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnVerNominaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        x = (String) jComboBox1.getSelectedItem();
        if (x.equals("ESTUDIANTES")) {
            jPanel4.setVisible(true);
        } else {
            jPanel4.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        metodo.SoloNumeros(evt, txtCedula);
        if (txtParalelo.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        try {
            bdReportes.reporte();
        } catch (JRException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        cedula = txtCedula.getText();
        if (cedula.length() < 10) {
            JOptionPane.showMessageDialog(null, "Error en la cédula ingresada");
        } else {
            try {
                bdReportes.DatosEstudiante(cedula);
            } catch (JRException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnInasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInasistenciaActionPerformed
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        try {
            bdReportes.listaInasistencia();
        } catch (JRException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInasistenciaActionPerformed

    private void btnDetallesAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesAsigActionPerformed
        jPanel6.setVisible(true);
        jPanel5.setVisible(false);

    }//GEN-LAST:event_btnDetallesAsigActionPerformed

    private void cbABasica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbABasica1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbABasica1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        if (metodo.Numero_añoBas(cbABasica) == 0) {
            JOptionPane.showMessageDialog(null, "Escoga el Año de Educación Básica");
        } else {
            try {
                bdReportes.ListaAsignaturas(metodo.Numero_añoBas(cbABasica));
            } catch (JRException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }
    private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Ayuda;
    private javax.swing.JDialog Creditos;
    private javax.swing.JButton btnAsignaturas;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnCalificaiones;
    private javax.swing.JButton btnComisiones;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnDetallesAsig;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnInasistencia;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btnModificarPersonas;
    private javax.swing.JButton btnRegistrarPersona;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalirSistema;
    private javax.swing.JButton btnVerNomina;
    private javax.swing.JButton btnVisualizarPersonas;
    private javax.swing.JComboBox cbABasica;
    private javax.swing.JComboBox cbABasica1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JFrame frmNomina;
    private javax.swing.JFrame frmRegistros;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHora;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtParalelo;
    // End of variables declaration//GEN-END:variables
}
